# Generated by Django 5.2.3 on 2025-07-07 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Extracted or manually entered job title",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description_text",
                    models.TextField(
                        blank=True, help_text="Extracted text from the PDF", null=True
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        help_text="The original uploaded PDF file",
                        upload_to="requirements_pdfs/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing_jd", "Processing Job Description"),
                            ("processed_jd", "Job Description Processed"),
                            ("failed_jd", "Job Description Processing Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "processing_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResumeBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zip_file",
                    models.FileField(
                        help_text="The original uploaded ZIP file",
                        upload_to="resume_zips/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("extracting", "Extracting Resumes"),
                            ("processing", "Processing Resumes"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "processing_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_batches",
                        to="resume_processor.jobrequirement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RankedResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Original filename of the resume PDF", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("extracted", "Text Extracted"),
                            ("ranked", "Ranked Successfully"),
                            ("failed_extraction", "Extraction Failed"),
                            ("failed_ranking", "Ranking Failed"),
                            ("text_too_short", "Text Too Short"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "extracted_info",
                    models.JSONField(
                        default=dict, help_text="JSON data of extracted candidate info"
                    ),
                ),
                (
                    "ranking_analysis",
                    models.JSONField(
                        default=dict, help_text="JSON data of ranking analysis"
                    ),
                ),
                (
                    "compatibility_score",
                    models.IntegerField(
                        default=0, help_text="Compatibility score from LLM (0-100)"
                    ),
                ),
                (
                    "candidate_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "candidate_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "resume_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranked_resumes",
                        to="resume_processor.resumebatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-compatibility_score"],
                "unique_together": {("resume_batch", "file_name")},
            },
        ),
    ]
